list_files:
  description: List files in a directory
  fields:
    path:
      description: Directory path
      required: true
      example: "/config"

upload_file:
  description: Upload a file
  fields:
    path:
      description: Destination path
      required: true
      example: "/config/test.txt"
    content:
      description: File content
      required: true
      example: "Hello World"

download_file:
  description: Download a file
  fields:
    path:
      description: File path
      required: true
      example: "/config/test.txt"

delete_file:
  description: Delete a file or directory
  fields:
    path:
      description: Path to delete
      required: true
      example: "/config/test.txt"

create_directory:
  description: Create a new directory
  fields:
    path:
      description: Directory path
      required: true
      example: "/config/new_folder"
